/**
 * A snapshot of the published template catalog (seeded content), used by the
 * catalog/recommendation tests so they exercise the real programs.
 */
import type { CatalogItem } from "./catalog";

export const CATALOG_FIXTURE: CatalogItem[] = [
  {
    slug: "fgpower-adaptation",
    namePt: "Adaptação FGPOWER — Força de Perna + Hipertrofia de Superior",
    taglinePt: "Uma progressão de 4 semanas para força de perna e hipertrofia de superior, 3x/semana.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "BEGINNER",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 4,
    sessionMinutes: 60,
    dayNames: ["Sessão A", "Sessão B", "Sessão C — Superior"],
  },
  {
    slug: "gd-adaptacao",
    namePt: "GD Adaptação",
    taglinePt:
      "Bloco 1 de 9 · semanas 1-4 (mês 1): aprenda os movimentos, calibre o RIR e prepare articulações e cargas para o GD 1, em cinco treinos de ~45-50 min.",
    goal: "HYPERTROPHY",
    experienceLevel: "BEGINNER",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 4,
    sessionMinutes: 47,
    dayNames: [
      "Segunda — Superior A (máquinas)",
      "Terça — Inferior A (quadríceps e posterior)",
      "Quarta — Técnica (corpo inteiro, leve)",
      "Quinta — Superior B (halteres e máquinas)",
      "Sexta — Inferior B (hack e glúteos)",
    ],
  },
  {
    slug: "gd-1",
    namePt: "GD 1",
    taglinePt:
      "Bloco 2 de 9 · semanas 5-17 (meses 2-4): base de hipertrofia em 5 dias, 80→88 séries por semana e o primeiro teste de força do plano.",
    goal: "HYPERTROPHY",
    experienceLevel: "BEGINNER",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 13,
    sessionMinutes: 55,
    dayNames: [
      "Segunda — Superior (pesado)",
      "Terça — Inferior (quadríceps, pesado)",
      "Quarta — Empurrar (moderado)",
      "Quinta — Puxar (moderado)",
      "Sexta — Pernas (posterior de coxa e glúteos)",
    ],
  },
  {
    slug: "gd-2",
    namePt: "GD 2",
    taglinePt:
      "Bloco 3 de 9 · semanas 18-30 (meses 5-7): força-hipertrofia com top sets + back-offs no supino e no hack; Superior/Inferior A-B + sexta de braços e ombros.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "UPPER_LOWER",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 13,
    sessionMinutes: 58,
    dayNames: [
      "Segunda — Superior A (pesado)",
      "Terça — Inferior A (pesado)",
      "Quarta — Superior B (moderado)",
      "Quinta — Inferior B (moderado, sem falha)",
      "Sexta — Braços, ombros e abdômen",
    ],
  },
  {
    slug: "gd-3",
    namePt: "GD 3",
    taglinePt:
      "Bloco 4 de 9 · semanas 31-43 (meses 8-10): o maior volume do ano 1, em Empurrar/Puxar/Pernas/Superior/Inferior, com novas âncoras de força.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 13,
    sessionMinutes: 58,
    dayNames: [
      "Segunda — Empurrar (peito, ombros, tríceps)",
      "Terça — Puxar (costas, bíceps)",
      "Quarta — Pernas (agachamento pesado)",
      "Quinta — Superior (moderado)",
      "Sexta — Inferior (posteriores e glúteos)",
    ],
  },
  {
    slug: "gd-4",
    namePt: "GD 4",
    taglinePt:
      "Bloco 5 de 9 · semanas 44-56 (meses 11-13): repetições altas, menos carga nas articulações, uma top set pesada por âncora e parciais alongadas — fecha o ano 1 com teste e revisão.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 13,
    sessionMinutes: 60,
    dayNames: [
      "Segunda — Superior (top sets + back-offs)",
      "Terça — Inferior (agachamento livre)",
      "Quarta — Empurrar (moderado)",
      "Quinta — Puxar (moderado)",
      "Sexta — Pernas (stiff + glúteos)",
    ],
  },
  {
    slug: "gd-5",
    namePt: "GD 5",
    taglinePt:
      "Bloco 6 de 9 · semanas 57-69 (meses 14-16, início do ano 2): especialização em que peito e deltoide lateral sobem até 20 e 18 séries semanais, enquanto o resto do corpo treina com ~25% menos volume.",
    goal: "HYPERTROPHY",
    experienceLevel: "ADVANCED",
    trainingStyle: "UPPER_LOWER",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 13,
    sessionMinutes: 55,
    dayNames: [
      "Segunda — Superior A (pesado + prioridade)",
      "Terça — Inferior A (quadríceps pesado)",
      "Quarta — Superior B (prioridade + volume)",
      "Quinta — Inferior B (posterior + glúteos)",
      "Sexta — Prioridade (peito + deltoide lateral)",
    ],
  },
  {
    slug: "gd-6",
    namePt: "GD 6",
    taglinePt:
      "Bloco 7 de 9 · semanas 70-82 (meses 17-19): top sets pesadas nas âncoras, 91 séries fixas por semana e progressão pela carga — força e músculo no mesmo bloco.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "ADVANCED",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 13,
    sessionMinutes: 58,
    dayNames: [
      "Segunda — Superior (pesado)",
      "Terça — Inferior (agachamento pesado)",
      "Quarta — Empurrar (desenvolvimento pesado + peito)",
      "Quinta — Puxar (costas + bíceps)",
      "Sexta — Pernas (terra romeno pesado)",
    ],
  },
  {
    slug: "gd-7",
    namePt: "GD 7",
    taglinePt:
      "Bloco 8 de 9 · semanas 83-95 (meses 20-22): especialização em posteriores de coxa e glúteos, treinados 3x por semana, com o resto do corpo em volume reduzido e as novas âncoras de força.",
    goal: "HYPERTROPHY",
    experienceLevel: "ADVANCED",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 13,
    sessionMinutes: 50,
    dayNames: [
      "Segunda — Empurrar + Prioridade (posteriores e glúteos)",
      "Terça — Puxar + Desenvolvimento",
      "Quarta — Pernas (agachamento pesado)",
      "Quinta — Superior (supino pesado)",
      "Sexta — Inferior (terra romeno + prioridade)",
    ],
  },
  {
    slug: "gd-8",
    namePt: "GD 8",
    taglinePt:
      "Bloco 9 de 9 · semanas 96-104 (meses 23-24): consolida os volumes que funcionaram, faz uma última onda com rampa de peito e costas e fecha com o teste final dos 2 anos.",
    goal: "HYPERTROPHY",
    experienceLevel: "ADVANCED",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 9,
    sessionMinutes: 59,
    dayNames: [
      "Segunda — Superior (pesado)",
      "Terça — Inferior (foco em quadríceps)",
      "Quarta — Empurrar (moderado)",
      "Quinta — Puxar (moderado)",
      "Sexta — Pernas (posterior + glúteos)",
    ],
  },
  {
    slug: "full-body-beginner",
    namePt: "Full Body Iniciante — Construa Sua Base",
    taglinePt: "Full body 3x por semana para aprender os movimentos e construir sua base — 8 semanas.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "BEGINNER",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 60,
    dayNames: ["Sessão A", "Sessão B", "Sessão C"],
  },
  {
    slug: "push-pull-legs",
    namePt: "FGPOWER Push/Pull/Legs — Hipertrofia 6x/Semana",
    taglinePt:
      "Seis sessões por semana, cada músculo treinado duas vezes — para o intermediário que quer ganhar massa.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "PUSH_PULL_LEGS",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 6,
    durationWeeks: 6,
    sessionMinutes: 70,
    dayNames: ["Push A", "Pull A", "Pernas A", "Push B", "Pull B", "Pernas B"],
  },
  {
    slug: "upper-lower",
    namePt: "Superior / Inferior — Força e Hipertrofia em 4 Dias",
    taglinePt:
      "Quatro dias por semana durante oito semanas: compostos pesados para força e acessórios em repetições altas para tamanho.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "UPPER_LOWER",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 8,
    sessionMinutes: 70,
    dayNames: [
      "Superior A — Ênfase em Empurrar",
      "Inferior A — Ênfase em Agachamento",
      "Superior B — Ênfase em Puxar",
      "Inferior B — Ênfase em Levantamento Terra",
    ],
  },
  {
    slug: "strength-fundamentals",
    namePt: "Força Fundamentos — Os Grandes Levantamentos com Barra",
    taglinePt:
      "Oito semanas de agachamento, supino, terra, desenvolvimento e remada — pesado, poucas reps, progressão linear.",
    goal: "STRENGTH",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 75,
    dayNames: [
      "Sessão A — Agachamento e Supino",
      "Sessão B — Terra e Desenvolvimento",
      "Sessão C — Agachamento Frontal e Inclinado",
    ],
  },
  {
    slug: "home-dumbbells",
    namePt: "Halteres em Casa — Base Full-Body para Iniciantes",
    taglinePt: "Treino full-body com halteres 3x na semana — uma base de 8 semanas para iniciantes, feita em casa.",
    goal: "HYPERTROPHY",
    experienceLevel: "BEGINNER",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "HOME_DUMBBELLS",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 55,
    dayNames: ["Corpo Inteiro A", "Corpo Inteiro B", "Corpo Inteiro C"],
  },
  {
    slug: "strength-for-runners",
    namePt: "Força para Corredores",
    taglinePt:
      "Força de perna mais pesada, um pouco de salto e core — três dias por semana para ganhar economia de corrida e resistência a lesões sem roubar as suas pernas.",
    goal: "SPORTS_PERFORMANCE",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "ENDURANCE_SUPPORT",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 55,
    dayNames: [
      "Sessão A — Agachamento e Saltos",
      "Sessão B — Dobradiça e Cadeia Posterior",
      "Sessão C — Potência e Unilateral",
    ],
  },
  {
    slug: "full-body-express",
    namePt: "Corpo Inteiro Express",
    taglinePt:
      "Dois treinos de corpo inteiro por semana, cerca de 40 minutos cada — a dose mínima eficaz para quem tem pouco tempo.",
    goal: "GENERAL_FITNESS",
    experienceLevel: "BEGINNER",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "HOME_DUMBBELLS",
    daysPerWeek: 2,
    durationWeeks: 6,
    sessionMinutes: 40,
    dayNames: ["Sessão A — Corpo Inteiro", "Sessão B — Corpo Inteiro"],
  },
  {
    slug: "glute-focus",
    namePt: "Glúteos & Posterior",
    taglinePt: "Especialização de 6 semanas para glúteos e posterior de coxa, 4x/semana, sem largar o resto do corpo.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 65,
    dayNames: [
      "Inferior A — Ênfase em Glúteo",
      "Superior A — Ênfase em Empurrar",
      "Inferior B — Ênfase em Posterior",
      "Superior B — Ênfase em Puxar",
    ],
  },
  {
    slug: "ppl-advanced",
    namePt: "PPL Sobrecarga no Alongamento — Avançado, 6×/semana",
    taglinePt:
      "Um Push/Pull/Legs de volume alto rodado 2x por semana, com viés para carregar cada músculo pesado onde ele está mais alongado.",
    goal: "HYPERTROPHY",
    experienceLevel: "ADVANCED",
    trainingStyle: "PUSH_PULL_LEGS",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 6,
    durationWeeks: 8,
    sessionMinutes: 75,
    dayNames: [
      "Push A — Pressão Pesada",
      "Pull A — Remada Pesada",
      "Legs A — Ênfase em Quadríceps",
      "Push B — Alongamento e Pump",
      "Pull B — Alongamento e Pump",
      "Legs B — Cadeia Posterior",
    ],
  },
  {
    slug: "arnold-split",
    namePt: "Arnold Antagonista — Split de Superséries Push-Pull",
    taglinePt:
      "O clássico split de 6 dias do Arnold, com peito contra costas e bíceps contra tríceps em superséries antagonistas para treinar os dois lados da articulação na mesma passada.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "BODY_PART_SPLIT",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 6,
    durationWeeks: 8,
    sessionMinutes: 70,
    dayNames: [
      "Peito & Costas — Pesado",
      "Ombro & Braço — Pesado",
      "Perna — Ênfase Agachamento",
      "Peito & Costas — Bomba",
      "Ombro & Braço — Bomba",
      "Perna — Cadeia Posterior",
    ],
  },
  {
    slug: "classic-split",
    namePt: "Divisão Clássica — Um Músculo por Dia",
    taglinePt:
      "A divisão clássica do fisiculturismo, feita com honestidade científica: um grande grupo por dia, volume alto por sessão e uma progressão que faz sentido.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "BODY_PART_SPLIT",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 8,
    sessionMinutes: 60,
    dayNames: ["Dia 1 — Peito", "Dia 2 — Costas", "Dia 3 — Pernas", "Dia 4 — Ombros", "Dia 5 — Braços"],
  },
  {
    slug: "torso-limbs",
    namePt: "Tronco & Membros Ondulado — Tensão e Bomba",
    taglinePt:
      "Um split tronco/membros que ondula cada região entre um dia pesado de tensão e um dia de bomba em altas repetições, 4x/semana por 8 semanas.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 8,
    sessionMinutes: 65,
    dayNames: ["Tronco — Tensão", "Membros — Tensão", "Tronco — Bomba", "Membros — Bomba"],
  },
  {
    slug: "powerbuilding",
    namePt: "Powerbuilding — Duas Marchas",
    taglinePt: "Duas marchas por semana para cada músculo: uma sessão pesada de força e uma de volume para tamanho.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "UPPER_LOWER",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 10,
    sessionMinutes: 70,
    dayNames: ["Superior — Força", "Inferior — Força", "Superior — Hipertrofia", "Inferior — Hipertrofia"],
  },
  {
    slug: "linear-5x5",
    namePt: "Alicerce 5×5 — Base de Força Linear",
    taglinePt:
      "Cinco exercícios, cinco séries de cinco, um pouco mais de peso a cada treino — o motor clássico de força pra iniciante, bem feito.",
    goal: "STRENGTH",
    experienceLevel: "BEGINNER",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 55,
    dayNames: ["Treino A", "Treino B"],
  },
  {
    slug: "strength-peak",
    namePt: "Pico de Força — Bloco de Intensidade",
    taglinePt:
      "4 semanas em que os grandes levantamentos rampam de 3-5 para 2-3 repetições pesadas — preparação de força, sem teste de 1RM.",
    goal: "STRENGTH",
    experienceLevel: "ADVANCED",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 4,
    sessionMinutes: 60,
    dayNames: ["Dia do Agachamento", "Dia do Supino", "Dia do Terra", "Dia do Desenvolvimento"],
  },
  {
    slug: "active-deload",
    namePt: "Deload Ativo — Semana de Recuperação",
    taglinePt:
      "Uma semana leve de corpo inteiro pra dissipar a fadiga entre blocos pesados — metade das séries, RIR 4-5, técnica impecável.",
    goal: "GENERAL_FITNESS",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 1,
    sessionMinutes: 40,
    dayNames: [
      "Sessão A — Corpo Inteiro em Máquinas",
      "Sessão B — Corpo Inteiro com Pesos Livres Leves",
      "Sessão C — Bomba nos Cabos",
    ],
  },
  {
    slug: "calisthenics",
    namePt: "Escada Corporal — Força e Volume só com o Peso do Corpo",
    taglinePt: "Sem peso, sem academia: você sobrecarrega subindo degraus de dificuldade, 3x/semana por 8 semanas.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "BEGINNER",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "HOME_BODYWEIGHT",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 50,
    dayNames: ["Sessão A — Fundamentos", "Sessão B — Puxada Vertical", "Sessão C — Empurrar & Unilateral"],
  },
  {
    slug: "kettlebell-strong",
    namePt: "Kettlebell Strong — Balísticos & Grinds",
    taglinePt:
      "Força e condicionamento full-body com kettlebell em 3 sessões densas por semana — balísticos explosivos pareados com grinds lentos, ao longo de 6 semanas.",
    goal: "GENERAL_FITNESS",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "MINIMAL",
    daysPerWeek: 3,
    durationWeeks: 6,
    sessionMinutes: 50,
    dayNames: ["A — Swing & Desenvolvimento", "B — Clean & Agachamento", "C — Snatch & Densidade"],
  },
  {
    slug: "dumbbell-upper-lower",
    namePt: "Tensão Alongada — Upper/Lower com Halteres",
    taglinePt:
      "Um bloco de hipertrofia de 8 semanas, 4x por semana, que caça crescimento na posição alongada — em casa, só com um par de halteres e um banco.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "UPPER_LOWER",
    equipmentAccess: "HOME_DUMBBELLS",
    daysPerWeek: 4,
    durationWeeks: 8,
    sessionMinutes: 60,
    dayNames: [
      "Superior A — Horizontal + Alongado",
      "Inferior A — Ênfase em Agachamento",
      "Superior B — Vertical + Alongado",
      "Inferior B — Ênfase Unilateral",
    ],
  },
  {
    slug: "minimalist-strength",
    namePt: "O Minimalista — Força em 2 Dias",
    taglinePt:
      "Cinco levantamentos com barra, dois treinos por semana, 50 minutos — a menor dose que ainda faz seus números subirem.",
    goal: "STRENGTH",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 2,
    durationWeeks: 8,
    sessionMinutes: 50,
    dayNames: ["Sessão A — Agachamento e Supino", "Sessão B — Terra e Desenvolvimento"],
  },
  {
    slug: "arms-specialization",
    namePt: "Braço em Dobro — Especialização de Bíceps e Tríceps em 6 Semanas",
    taglinePt:
      "Dois dias de martelo nos braços e dois de manutenção: um bloco focado pra empurrar os braços enquanto o resto do corpo só se mantém.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 55,
    dayNames: [
      "Braço A — Cotovelos com Ênfase de Empurrar",
      "Manutenção — Inferior",
      "Braço B — Cotovelos com Ênfase de Puxar",
      "Manutenção — Superior",
    ],
  },
  {
    slug: "back-focus",
    namePt: "Costas em Destaque — Especialização em Largura & Densidade",
    taglinePt:
      "Uma especialização de costas de 6 semanas: quatro sessões de puxada por semana, pegadas alternadas para largura e densidade, com o resto do corpo em manutenção.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 60,
    dayNames: [
      "Largura A — Aberta & Pronada",
      "Densidade A — Remada Pesada",
      "Largura B — Supinada & Neutra",
      "Densidade B — Remada de Detalhe & Trapézio",
    ],
  },
  {
    slug: "chest-focus",
    namePt: "Peito em Destaque",
    taglinePt:
      "Uma especialização de 6 semanas que ataca o peito em três ângulos, três vezes por semana, enquanto o resto do corpo trabalha em manutenção.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 60,
    dayNames: [
      "Dia A — Supino Reto Pesado",
      "Dia B — Manutenção de Perna",
      "Dia C — Ênfase Inclinada",
      "Dia D — Crucifixos e Cross Over",
    ],
  },
  {
    slug: "delts-3d",
    namePt: "Ombros 3D — Deltoides Completos",
    taglinePt:
      "Especialização de 6 semanas pra construir ombros redondos nos três ângulos — lateral, anterior e posterior — batendo delt 4x na semana.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 55,
    dayNames: ["Pressão & Largura", "Posterior & Braço", "Altura & Força", "Densidade & Bombeamento"],
  },
  {
    slug: "legs-specialization",
    namePt: "Pernas em Foco — Especialização de Quadríceps & Posterior",
    taglinePt:
      "Um bloco de 8 semanas de especialização de pernas: dois dias de perna de alto volume e dois dias enxutos de manutenção de superior.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 8,
    sessionMinutes: 70,
    dayNames: [
      "Perna A — Quadríceps",
      "Superior A — Suporte (Ênfase Empurrar)",
      "Perna B — Posterior & Glúteo",
      "Superior B — Suporte (Ênfase Puxar)",
    ],
  },
  {
    slug: "lengthened-partials",
    namePt: "Tensão no Alongamento — Hipertrofia em Posição Alongada",
    taglinePt:
      "Carregue cada músculo onde ele é mais comprido — um bloco upper/lower de 6 semanas construído em torno da posição alongada.",
    goal: "HYPERTROPHY",
    experienceLevel: "ADVANCED",
    trainingStyle: "UPPER_LOWER",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 65,
    dayNames: [
      "Superior A — Tensão no Alongamento (ênfase empurrar)",
      "Inferior A — Quadríceps em Alongamento",
      "Superior B — Tensão no Alongamento (ênfase puxar)",
      "Inferior B — Cadeia Posterior em Alongamento",
    ],
  },
  {
    slug: "tempo-control",
    namePt: "Controle de Tempo — Cadência & Excêntrica",
    taglinePt:
      "Seis semanas de cadência controlada e ênfase na fase excêntrica com cargas moderadas — full-body, 3x/semana.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 6,
    sessionMinutes: 60,
    dayNames: ["Sessão A — Excêntrica nos Compostos", "Sessão B — Cadência Constante", "Sessão C — Pausa no Alongado"],
  },
  {
    slug: "metabolite-pump",
    namePt: "Pump Metabólico — Hipertrofia de Alto Volume e Descanso Curto",
    taglinePt:
      "Hipertrofia de alto volume e descanso curto em ~55 minutos: 4 dias upper/lower, repetições 12-20 e a verdade sobre por que o descanso ainda importa.",
    goal: "HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "UPPER_LOWER",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 55,
    dayNames: [
      "Superior A — Bomba de Peito e Braço",
      "Inferior A — Ênfase em Quadríceps",
      "Superior B — Bomba de Costas e Ombro",
      "Inferior B — Ênfase em Glúteo e Posterior",
    ],
  },
  {
    slug: "silver-strength-50plus",
    namePt: "Força na Maturidade 50+ — Fundamentos de Corpo Inteiro",
    taglinePt:
      "Força funcional aos 50+ em 8 semanas: máquinas, amplitude confortável e os movimentos que mantêm você independente.",
    goal: "GENERAL_FITNESS",
    experienceLevel: "BEGINNER",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 50,
    dayNames: ["Sessão A — Levantar e Empurrar", "Sessão B — Puxar e Carregar", "Sessão C — Posterior e Estabilidade"],
  },
  {
    slug: "desk-worker",
    namePt: "Antídoto do Escritório — Postura & Costas",
    taglinePt:
      "Um full-body de 6 semanas, puxada-dominante, pra desfazer o estrago de ficar sentado — 3x/semana, feito pra iniciantes.",
    goal: "GENERAL_FITNESS",
    experienceLevel: "BEGINNER",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 6,
    sessionMinutes: 45,
    dayNames: [
      "Sessão A — Descompressão Vertical",
      "Sessão B — Retração & Ancoragem",
      "Sessão C — Extensão & Blindagem",
    ],
  },
  {
    slug: "machines-only-beginner",
    namePt: "Sem Medo das Máquinas — Full Body Guiado para Iniciantes",
    taglinePt:
      "8 semanas guiadas para dominar a sala de musculação inteira sem tocar em nenhuma barra livre, 3x por semana.",
    goal: "GENERAL_FITNESS",
    experienceLevel: "BEGINNER",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 50,
    dayNames: ["Sessão A — Fundamentos", "Sessão B — Variações Guiadas", "Sessão C — Base Completa"],
  },
  {
    slug: "athletic-power",
    namePt: "Potência Atlética — Explosão",
    taglinePt: "Compostos pesados + pliometria e arremessos, 4x/semana por 6 semanas — força que vira velocidade.",
    goal: "SPORTS_PERFORMANCE",
    experienceLevel: "ADVANCED",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 6,
    sessionMinutes: 60,
    dayNames: [
      "Potência Inferior A — Agachamento e Saltos",
      "Potência Superior A — Empurrar e Arremessos",
      "Potência Inferior B — Terra e Saltos Reativos",
      "Potência Superior B — Desenvolvimento e Puxada",
    ],
  },
  {
    slug: "combat-sports",
    namePt: "Base do Lutador — Força para Atletas de Combate",
    taglinePt:
      "Força full-body, pegada e core anti-rotação para lutadores — pesado o bastante para contar, leve o bastante para sobrar gás pro tatame.",
    goal: "SPORTS_PERFORMANCE",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 55,
    dayNames: ["Sessão A — Soco & Base", "Sessão B — Puxão & Dobradiça", "Sessão C — Giro & Blindagem"],
  },
  {
    slug: "cyclists-strength",
    namePt: "Torque — Base de Força para Ciclistas",
    taglinePt:
      "Duas sessões curtas por semana para construir força de perna que vira watt — sem roubar suas pernas do pedal.",
    goal: "SPORTS_PERFORMANCE",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "ENDURANCE_SUPPORT",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 2,
    durationWeeks: 8,
    sessionMinutes: 45,
    dayNames: ["Sessão A — Agachamento e Anti-Rotação", "Sessão B — Leg Press e Extensão de Quadril"],
  },
  {
    slug: "climbers-pull",
    namePt: "Força para Escaladores — Puxada & Preensão",
    taglinePt:
      "Oito semanas construindo força de puxada, preensão de antebraço e um core anti-movimento — com empurrar para equilibrar o ombro. 3x/semana.",
    goal: "SPORTS_PERFORMANCE",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 55,
    dayNames: ["Sessão A — Puxada Pesada", "Sessão B — Volume de Costas & Antebraço", "Sessão C — Preensão & Contato"],
  },
  {
    slug: "hybrid-athlete",
    namePt: "Atleta Híbrido — Força e Motor",
    taglinePt:
      "Força e hipertrofia sem abrir mão do fôlego: um Upper/Lower de 4 dias que encaixa o condicionamento onde ele menos atrapalha.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 4,
    durationWeeks: 8,
    sessionMinutes: 65,
    dayNames: [
      "Inferior A — Força de Agachamento",
      "Superior A — Força de Empurrar + Motor VO2",
      "Inferior B — Terra e Unilateral",
      "Superior B — Hipertrofia de Puxar + Zona 2",
    ],
  },
  {
    slug: "full-body-strength-hyp-3",
    namePt: "Full Body Ancorado — Força e Hipertrofia 3x",
    taglinePt:
      "Cada treino abre com um grande levantamento pesado e constrói músculo em volta dele — agachamento, supino e terra ancoram um dia cada.",
    goal: "STRENGTH_HYPERTROPHY",
    experienceLevel: "INTERMEDIATE",
    trainingStyle: "FULL_BODY",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 3,
    durationWeeks: 8,
    sessionMinutes: 65,
    dayNames: ["Sessão A — Âncora: Agachamento", "Sessão B — Âncora: Supino", "Sessão C — Âncora: Terra"],
  },
  {
    slug: "high-frequency-squat",
    namePt: "Agachamento Diário — Alta Frequência Autorregulada",
    taglinePt: "Agache 5 dias por semana com intensidade autorregulada por RIR — um bloco avançado de 6 semanas.",
    goal: "STRENGTH",
    experienceLevel: "ADVANCED",
    trainingStyle: "HYBRID",
    equipmentAccess: "FULL_GYM",
    daysPerWeek: 5,
    durationWeeks: 6,
    sessionMinutes: 55,
    dayNames: [
      "Segunda — Pesado",
      "Terça — Frontal",
      "Quinta — Volume",
      "Sexta — Controle na Caixa",
      "Sábado — Velocidade",
    ],
  },
];
