import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ChevronLeft } from "lucide-react";
import { getCurrentSession, requireUser } from "@/lib/auth/require-user";
import { prisma } from "@/lib/db";
import { NOT_FOUND_TITLE } from "@/components/ui/not-found-panel";
import { Button } from "@/components/ui/button";
import { correctableUntil, isStillEditable } from "@/lib/data/workout-session";
import { formatDecimal, isTimedHold } from "@/lib/training/set-plan";
import { formatSpTime } from "@/lib/training/stale";
import { formatSpShortDate } from "../dossier";
import { EditSetsForm, type EditableExercise } from "./edit-sets-form";

/** The route's props (spelled out: typed routes are generated by the dev server). */
type Props = { params: Promise<{ sessionId: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { sessionId } = await params;
  const auth = await getCurrentSession();
  const workout = auth
    ? await prisma.workoutSession.findUnique({ where: { id: sessionId }, select: { name: true, userId: true } })
    : null;
  return workout && workout.userId === auth?.user.id ? { title: `Editar séries · ${workout.name}` } : { title: NOT_FOUND_TITLE };
}

/**
 * "Editar séries" (W-088): a finished workout's sets that counted, to correct
 * (a typo: "225" for 22,5) or take out, for a day after it was finished.
 * Saving recomputes its totals and records (editFinishedWorkout).
 */
export default async function EditFinishedWorkoutPage({ params }: Props) {
  const { sessionId } = await params;
  const user = await requireUser();
  const session = await prisma.workoutSession.findFirst({
    where: { id: sessionId, userId: user.id },
    select: {
      id: true,
      name: true,
      status: true,
      finishedAt: true,
      updatedAt: true,
      exerciseLogs: {
        orderBy: { sortOrder: "asc" },
        select: {
          id: true,
          notes: true,
          exercise: { select: { namePt: true, slug: true } },
          sets: {
            where: { isCompleted: true, setType: { not: "WARMUP" } },
            orderBy: { setNumber: "asc" },
            select: { id: true, isExtra: true, weightKg: true, reps: true, rir: true },
          },
        },
      },
    },
  });
  if (!session) notFound();
  if (session.status === "IN_PROGRESS") redirect(`/app/workout/${sessionId}`);
  if (session.status !== "COMPLETED" || !session.finishedAt) notFound();
  const summaryHref = `/app/workout/${sessionId}/summary`;

  const header = (
    <>
      <Link
        href={summaryHref}
        className="-ml-1 inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-accent hover:underline"
      >
        <ChevronLeft className="size-4" />
        Resumo
      </Link>
      <p className="mt-2 font-mono text-xs font-bold uppercase tracking-[0.18em] text-muted">
        Editar séries · <span className="whitespace-nowrap">{formatSpShortDate(session.finishedAt)}</span>
      </p>
      <h1 className="text-display mt-1 text-3xl font-extrabold tracking-tight wrap-break-word">{session.name}</h1>
    </>
  );

  const saved = { finishedAt: session.finishedAt, updatedAt: session.updatedAt };
  if (!isStillEditable(saved)) {
    return (
      <div className="mx-auto max-w-2xl px-4 py-6 sm:px-6 sm:py-10">
        {header}
        <p className="mt-4 border-l-2 border-l-warning bg-warning-soft px-3 py-2.5 text-sm text-foreground/90">
          O prazo para corrigir este treino acabou: as séries podem ser editadas até 24 h depois de salvo.
        </p>
        <Button className="mt-5" variant="outline" asChild>
          <Link href={summaryHref}>Voltar ao resumo</Link>
        </Button>
      </div>
    );
  }

  const until = correctableUntil(saved);
  const exercises: EditableExercise[] = session.exerciseLogs
    .filter((log) => log.sets.length > 0)
    .map((log) => {
      let prescribed = 0;
      let extra = 0;
      return {
        logId: log.id,
        name: log.exercise.namePt,
        timed: isTimedHold({ slug: log.exercise.slug, notes: log.notes }),
        sets: log.sets.map((s) => ({
          id: s.id,
          label: s.isExtra ? `E${++extra}` : String(++prescribed),
          name: s.isExtra ? `Série extra ${extra}` : `Série ${prescribed}`,
          weight: formatDecimal(s.weightKg),
          reps: formatDecimal(s.reps),
          rir: formatDecimal(s.rir),
        })),
      };
    });

  return (
    <div className="mx-auto max-w-2xl px-4 py-6 sm:px-6 sm:py-10">
      {header}
      <p className="mt-2 text-sm text-muted">
        Corrija uma carga ou reps digitadas errado, ou tire uma série que não aconteceu. Os recordes e o volume são
        recalculados. Dá para corrigir até {formatSpShortDate(until)}, {formatSpTime(until)}.
      </p>
      <EditSetsForm sessionId={session.id} exercises={exercises} summaryHref={summaryHref} />
    </div>
  );
}
